#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      off
yabai -m config window_shadow                on
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  12
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   06

# specific apps
#yabai -m rule --add app!="^(Google Chrome|Spotify|Emacs|Slack|Skype|Telegram|Discord|kitty|GoLand|MySQLWorkbench|League of Legends|SnippetsLab|Finder|Messenger|Todoist|Dash|zoom.us|Firefox)$" space=1
# TODO ohh I can make the order.py run on display changed as a script maybe?
yabai -m rule --add app!="^Preview$" space=1

yabai -m rule --add app=Emacs manage=on
yabai -m rule --add app="^Alfred$" sticky=on

my_dir="$(dirname "$0")"

chmod +x "$my_dir/yabairc-trait"
"$my_dir/yabairc-trait"

echo "yabai configuration loaded.."

# LOGGING:
# directory containing log files (HOMEBREW_PREFIX defaults to /usr/local unless you manually specified otherwise)
#HOMEBREW_PREFIX/var/log/yabai/
# view the last lines of the error log 
#tail -f /usr/local/var/log/yabai/yabai.err.log
# view the last lines of the debug log
#tail -f /usr/local/var/log/yabai/yabai.out.log

